### ISSUE TITLE
Issue 2

### ISSUE THREAD

**Issue by JimHuntStink** [JimHuntStink/Test-Repo#2]
This is issue 2

- [x] Part one
- [x] Section two to do
- [ ] Bit three as well

**Comment by JimHuntStink** [comment]
- [ ] Part one
- [ ] Section two to do
- [ ] Bit three as well

**Comment by JimHuntStink** [comment]
#4

**Comment by JimHuntStink** [comment]
`if this == 'that' then something()`
